package de.jworks.datahub.presentation.views;

import java.util.Arrays;

import javax.annotation.PostConstruct;
import javax.inject.Inject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.Table.ColumnGenerator;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

import de.jworks.datahub.business.common.boundary.UserService;
import de.jworks.datahub.business.common.entity.User;
import de.jworks.datahub.presentation.Messages;
import de.jworks.datahub.presentation.editors.UserEditor;
import de.jworks.datahub.presentation.editors.UserEditor.SaveEvent;
import de.jworks.datahub.presentation.editors.UserEditor.SaveListener;

public class AdminViewUsers extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout buttons;
	@AutoGenerated
	private Button addUserButton;
	@AutoGenerated
	private Table table;
	@AutoGenerated
	private Label label;
	
	@Inject
	UserService userService;
	
	private BeanItemContainer<User> users = new BeanItemContainer<User>(User.class);
	
	public AdminViewUsers() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		Messages.translate(this);
		
		table.addGeneratedColumn("actions", new ActionsColumn());
		
		table.setContainerDataSource(users, Arrays.asList("id", "name", "fullName", "email", "roles", "actions"));
		table.setColumnHeader("name", Messages.getString(this, "name"));
		table.setColumnHeader("fullName", Messages.getString(this, "fullName"));
		table.setColumnHeader("email", Messages.getString(this, "email"));
		table.setColumnHeader("roles", Messages.getString("roles"));
		table.setColumnHeader("actions", Messages.getString("actions"));
//		table.setColumnExpandRatio("id", 1.0f);
		table.setColumnExpandRatio("name", 1.0f);
		table.setColumnExpandRatio("fullName", 1.0f);
		table.setColumnExpandRatio("email", 1.0f);
		table.setColumnExpandRatio("roles", 1.0f);

		addUserButton.addClickListener(new AddUserHandler());
	}

	@PostConstruct
	public void refreshTable() {
		users.removeAllItems();
		users.addAll(userService.getUsers());
	}

	private class ActionsColumn implements ColumnGenerator {
		
		@Override
		public Object generateCell(Table source, Object itemId, Object columnId) {
			User user = users.getItem(itemId).getBean();
			HorizontalLayout actions = new HorizontalLayout();
			actions.setSpacing(true);
			actions.addComponent(new EditUserButton(user));
			actions.addComponent(new DeleteUserButton(user));
			return actions;
		}
		
	}

	private class EditUserButton extends Button implements ClickListener {
		
		private User user;
		
		public EditUserButton(User user) {
			this.user = user;
			
			setCaption(Messages.getString("edit"));
			setStyleName("link");
			
			addClickListener(this);
		}
		
		@Override
		public void buttonClick(ClickEvent event) {
			final Window window = new Window(Messages.format("editUser", user.getId()));
			window.setModal(true);
			window.setDraggable(false);
			window.setResizable(false);
			window.addCloseListener(new CloseListener() {
				@Override
				public void windowClose(CloseEvent e) {
					refreshTable();
				}
			});
			
			UserEditor editor = new UserEditor(user);
			editor.addSaveListener(new SaveListener() {
				@Override
				public void save(SaveEvent event) {
					if (event.getUser() != null) {
						userService.updateUser(event.getUser());
					}
					window.close();
				}
			});
			window.setContent(editor);
			
			UI.getCurrent().addWindow(window);
		}
		
	}
	
	private class DeleteUserButton extends Button implements ClickListener {
		
		private User user;
		
		public DeleteUserButton(User user) {
			this.user = user;
			
			setCaption(Messages.getString("delete"));
			setStyleName("link");
			
			addClickListener(this);
		}
		
		@Override
		public void buttonClick(ClickEvent event) {
			userService.removeUser(user);
			refreshTable();
		}
		
	}
	
	private class AddUserHandler implements ClickListener {
		
		@Override
		public void buttonClick(ClickEvent event) {
			final Window window = new Window(Messages.getString("newUser"));
			window.setModal(true);
			window.setDraggable(false);
			window.setResizable(false);
			window.addCloseListener(new CloseListener() {
				@Override
				public void windowClose(CloseEvent e) {
					refreshTable();
				}
			});
			
			UserEditor editor = new UserEditor(new User());
			editor.addSaveListener(new SaveListener() {
				@Override
				public void save(SaveEvent event) {
					if (event.getUser() != null) {
						userService.addUser(event.getUser());
					}
					window.close();
				}
			});
			window.setContent(editor);
			
			UI.getCurrent().addWindow(window);
		}
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label
		label = new Label();
		label.setStyleName("h1");
		label.setImmediate(false);
		label.setWidth("-1px");
		label.setHeight("-1px");
		label.setValue("Users");
		mainLayout.addComponent(label);
		
		// table
		table = new Table();
		table.setImmediate(false);
		table.setWidth("100.0%");
		table.setHeight("100.0%");
		mainLayout.addComponent(table);
		mainLayout.setExpandRatio(table, 1.0f);
		
		// buttons
		buttons = buildButtons();
		mainLayout.addComponent(buttons);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildButtons() {
		// common part: create layout
		buttons = new HorizontalLayout();
		buttons.setImmediate(false);
		buttons.setWidth("-1px");
		buttons.setHeight("-1px");
		buttons.setMargin(false);
		buttons.setSpacing(true);
		
		// addUserButton
		addUserButton = new Button();
		addUserButton.setStyleName("small");
		addUserButton.setCaption("Add User...");
		addUserButton.setImmediate(false);
		addUserButton.setWidth("-1px");
		addUserButton.setHeight("-1px");
		buttons.addComponent(addUserButton);
		
		return buttons;
	}

}
