package de.jworks.datahub.presentation.views;

import java.util.Arrays;

import javax.annotation.PostConstruct;
import javax.inject.Inject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.Table.ColumnGenerator;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.Window.CloseEvent;
import com.vaadin.ui.Window.CloseListener;

import de.jworks.datahub.business.projects.boundary.ProjectService;
import de.jworks.datahub.business.systems.boundary.SystemService;
import de.jworks.datahub.business.systems.entity.System;
import de.jworks.datahub.presentation.editors.SystemEditor;
import de.jworks.datahub.presentation.editors.SystemEditor.SaveEvent;
import de.jworks.datahub.presentation.editors.SystemEditor.SaveListener;

public class AdminViewSystems extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout buttons;
	@AutoGenerated
	private Button newSystemButton;
	@AutoGenerated
	private Table table;
	@AutoGenerated
	private Label label;
	
	@Inject
	SystemService systemService;
	
	@Inject
	ProjectService projectService;
	
	private BeanItemContainer<System> systems = new BeanItemContainer<System>(System.class);
	
	public AdminViewSystems() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		table.setSelectable(true);
		table.setMultiSelect(true);
		
		table.addGeneratedColumn("actions", new ActionsColumn());
		
		table.setContainerDataSource(systems, Arrays.asList("id", "name", "project", "actions"));
		table.setColumnExpandRatio("name", 1.0f);
		table.setColumnExpandRatio("project", 1.0f);
		
		newSystemButton.addClickListener(new NewSystemHandler());
	}

	@PostConstruct
	public void refreshTable() {
		systems.removeAllItems();
		systems.addAll(systemService.getSystems());
	}

	private class NewSystemHandler implements ClickListener {
		
		@Override
		public void buttonClick(ClickEvent event) {
			final Window window = new Window("New System");
			window.setWidth("90%");
			window.setHeight("90%");
			window.setModal(true);
			window.setDraggable(false);
			window.setResizable(false);
			window.addCloseListener(new CloseListener() {
				@Override
				public void windowClose(CloseEvent e) {
					refreshTable();
				}
			});
			
			SystemEditor editor = new SystemEditor(new System(), projectService.getProjects());
			editor.addSaveListener(new SaveListener() {
				@Override
				public void save(SaveEvent event) {
					if (event.getSystem() != null) {
						systemService.addSystem(event.getSystem());
					}
					window.close();
				}
			});
			window.setContent(editor);
			
			UI.getCurrent().addWindow(window);
		}
		
	}

	private class ActionsColumn implements ColumnGenerator {
		
		@Override
		public Object generateCell(Table source, Object itemId, Object columnId) {
			System system = systems.getItem(itemId).getBean();
			HorizontalLayout actions = new HorizontalLayout();
			actions.setSpacing(true);
			actions.addComponent(new EditSystemButton(system));
			actions.addComponent(new DeleteSystemButton(system));
			return actions;
		}
	}

	private class EditSystemButton extends Button implements ClickListener {
		
		private System system;
		
		public EditSystemButton(System system) {
			this.system = system;
			
			setCaption("edit");
			setStyleName("link");
			
			addClickListener(this);
		}
		
		@Override
		public void buttonClick(ClickEvent event) {
			final Window window = new Window(String.format("Edit System '%s'", system.getName()));
			window.setSizeFull();
			window.setModal(true);
			window.setDraggable(false);
			window.setResizable(false);
			window.addCloseListener(new CloseListener() {
				@Override
				public void windowClose(CloseEvent e) {
					refreshTable();
				}
			});
			
			SystemEditor editor = new SystemEditor(system, projectService.getProjects());
			editor.addSaveListener(new SaveListener() {
				@Override
				public void save(SaveEvent event) {
					if (event.getSystem() != null) {
						systemService.updateSystem(event.getSystem());
					}
					window.close();
				}
			});
			window.setContent(editor);
			
			UI.getCurrent().addWindow(window);
		}
		
	}
	
	private class DeleteSystemButton extends Button implements ClickListener {
		
		private System system;
		
		public DeleteSystemButton(System system) {
			this.system = system;
			
			setCaption("delete");
			setStyleName("link");
			
			addClickListener(this);
		}
		
		@Override
		public void buttonClick(ClickEvent event) {
			systemService.removeSystem(system);
		}
		
	}
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label
		label = new Label();
		label.setStyleName("h1");
		label.setImmediate(false);
		label.setWidth("-1px");
		label.setHeight("-1px");
		label.setValue("Systems");
		mainLayout.addComponent(label);
		
		// table
		table = new Table();
		table.setImmediate(false);
		table.setWidth("100.0%");
		table.setHeight("100.0%");
		mainLayout.addComponent(table);
		mainLayout.setExpandRatio(table, 1.0f);
		
		// buttons
		buttons = buildButtons();
		mainLayout.addComponent(buttons);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildButtons() {
		// common part: create layout
		buttons = new HorizontalLayout();
		buttons.setImmediate(false);
		buttons.setWidth("-1px");
		buttons.setHeight("-1px");
		buttons.setMargin(false);
		buttons.setSpacing(true);
		
		// newSystemButton
		newSystemButton = new Button();
		newSystemButton.setStyleName("small");
		newSystemButton.setCaption("New System...");
		newSystemButton.setImmediate(false);
		newSystemButton.setWidth("-1px");
		newSystemButton.setHeight("-1px");
		buttons.addComponent(newSystemButton);
		
		return buttons;
	}

}
