package de.jworks.datahub.presentation.views;

import java.util.Arrays;

import javax.annotation.PostConstruct;
import javax.inject.Inject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

import de.jworks.datahub.business.projects.boundary.ProjectService;
import de.jworks.datahub.business.projects.entity.Project;
import de.jworks.datahub.presentation.Constants;
import de.jworks.datahub.presentation.Messages;

public class UserViewProjects extends CustomComponent implements Constants {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table table;
	@AutoGenerated
	private Label label;
	
	@Inject
	ProjectService projectService;
	
	private BeanItemContainer<Project> projects = new BeanItemContainer<Project>(Project.class);
	
	public UserViewProjects() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		table.setContainerDataSource(projects, Arrays.asList("name", "description"));
		table.addItemClickListener(new EditProjectHandler());
		
		label.setValue(Messages.getString("projects"));
	}
	
	@PostConstruct
	public void refreshTable() {
		projects.removeAllItems();
		projects.addAll(projectService.getProjects());
	}

	private class EditProjectHandler implements ItemClickListener {
	
		@Override
		public void itemClick(ItemClickEvent event) {
			Project project = projects.getItem(event.getItemId()).getBean();
			UI.getCurrent().getNavigator().navigateTo(String.format(USER_VIEW_PROJECT, project.getId()));
		}
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label
		label = new Label();
		label.setStyleName("h1");
		label.setImmediate(false);
		label.setWidth("-1px");
		label.setHeight("-1px");
		label.setValue("Projects");
		mainLayout.addComponent(label);
		
		// table
		table = new Table();
		table.setImmediate(false);
		table.setWidth("100.0%");
		table.setHeight("100.0%");
		mainLayout.addComponent(table);
		mainLayout.setExpandRatio(table, 1.0f);
		
		return mainLayout;
	}

}
