package de.jworks.datahub.presentation.views;

import javax.inject.Inject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.cdi.CDIView;
import com.vaadin.cdi.access.AccessControl;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.Page;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Panel;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

import de.jworks.datahub.business.common.boundary.UserService;
import de.jworks.datahub.business.common.entity.Project;
import de.jworks.datahub.business.common.entity.Role;
import de.jworks.datahub.business.datasets.boundary.DatasetService;
import de.jworks.datahub.business.projects.boundary.ProjectService;
import de.jworks.datahub.presentation.Constants;
import de.jworks.datahub.presentation.Messages;
import de.jworks.datahub.presentation.editors.UserEditor;

@CDIView
//@RolesAllowed({ Role.USER })
public class UserView extends CustomComponent implements View, Constants {
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout menuBars;
	@AutoGenerated
	private MenuBar menuBar_1;
	@AutoGenerated
	private MenuBar menuBar_2;
	@AutoGenerated
	private Panel panel;
	@AutoGenerated
	private VerticalLayout panelContent;
	
	@Inject
	AccessControl accessControl;
	@Inject
	UserService userService;
	@Inject
	ProjectService projectService;
	@Inject
	DatasetService documentService;
	@Inject
	UserViewTasks tasksComponent;
	@Inject
	UserViewProjects projectsComponent;
	@Inject
	UserViewProject projectComponent;
	
	private MenuItem userItem;
	private MenuItem adminItem;

	public UserView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		menuBar_1.setAutoOpen(true);
		menuBar_1.setHtmlContentAllowed(true);
		menuBar_1.addItem(USER_VIEW_CAPTION, new NavigateTo(USER_VIEW));
		menuBar_1.addItem(Messages.getString("tasks"), new NavigateTo(USER_VIEW_TASKS));
		menuBar_1.addItem(Messages.getString("projects"), new NavigateTo(USER_VIEW_PROJECTS));
		menuBar_1.addItem(Messages.getString("actions"), new NavigateTo(USER_VIEW_ACTIONS));
		
		menuBar_2.setAutoOpen(true);
		menuBar_2.setHtmlContentAllowed(true);
		menuBar_2.addItem(Messages.getString("search"), new Search());
		
		adminItem = menuBar_2.addItem(Messages.getString("administration"), new NavigateTo(ADMIN_VIEW));
		
		userItem = menuBar_2.addItem("", null);
		userItem.addItem(Messages.getString("editProfile"), new EditProfile());
		userItem.addSeparator();
		userItem.addItem(Messages.getString(SIGN_OUT), new NavigateTo(LOGIN_VIEW));
	}
	
	@Override
	public void enter(ViewChangeEvent event) {
		userItem.setText(String.format("%s ▼", userService.getCurrentUser()));
		
		adminItem.setVisible(accessControl.isUserInRole(Role.ADMIN));
		
		String[] parameters = event.getParameters().split("/");
		if (TASKS.equals(parameters[0])) {
			Page.getCurrent().setTitle(TITLE_PREFIX + Messages.getString(TASKS));
			panel.setContent(tasksComponent);
			tasksComponent.refreshTable();
		} else if (PROJECTS.equals(parameters[0])) {
			if (parameters.length > 1) {
				long projectId = Long.parseLong(parameters[1]);
				Project project = projectService.getProject(projectId);
				Page.getCurrent().setTitle(TITLE_PREFIX + project.getName());
				panel.setContent(projectComponent);
				projectComponent.setProject(project);
			} else {
				Page.getCurrent().setTitle(TITLE_PREFIX + Messages.getString(PROJECTS));
				panel.setContent(projectsComponent);
				projectsComponent.refreshTable();
			}
		} else if (ACTIONS.equals(parameters[0])) {
			Page.getCurrent().setTitle(TITLE_PREFIX + Messages.getString(ACTIONS));
			panel.setContent(panelContent);
		} else {
			UI.getCurrent().getNavigator().navigateTo(USER_VIEW_TASKS);
		}
	}
	
	public class NavigateTo implements Command {
		
		private String navigationState;
		
		public NavigateTo(String navigationState) {
			this.navigationState = navigationState;
		}

		@Override
		public void menuSelected(MenuItem selectedItem) {
			UI.getCurrent().getNavigator().navigateTo(navigationState);
		}
		
	}
	
	private class Search implements Command {

		@Override
		public void menuSelected(MenuItem selectedItem) {
			Window window = new Window("Search");
			window.setSizeFull();
			window.setModal(true);
			window.setDraggable(false);
			window.setResizable(false);
			UI.getCurrent().addWindow(window);
		}
		
	}
	
	public class EditProfile implements Command {
		
		@Override
		public void menuSelected(MenuItem selectedItem) {
			final Window window = new Window("Edit Profile");
			window.setModal(true);
			window.setDraggable(false);
			window.setResizable(false);
			
			UserEditor editor = new UserEditor(userService.getCurrentUser());
			editor.addSaveListener(new UserEditor.SaveListener() {
				@Override
				public void save(UserEditor.SaveEvent event) {
					if (event.getUser() != null) {
						userService.updateUser(event.getUser());
					}
					window.close();
				}
			});
			window.setContent(editor);
			
			UI.getCurrent().addWindow(window);
		}
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// menuBars
		menuBars = buildMenuBars();
		mainLayout.addComponent(menuBars);
		
		// panel
		panel = buildPanel();
		mainLayout.addComponent(panel);
		mainLayout.setExpandRatio(panel, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildMenuBars() {
		// common part: create layout
		menuBars = new HorizontalLayout();
		menuBars.setImmediate(false);
		menuBars.setWidth("100.0%");
		menuBars.setHeight("-1px");
		menuBars.setMargin(false);
		
		// menuBar_1
		menuBar_1 = new MenuBar();
		menuBar_1.setImmediate(false);
		menuBar_1.setWidth("100.0%");
		menuBar_1.setHeight("-1px");
		menuBars.addComponent(menuBar_1);
		menuBars.setExpandRatio(menuBar_1, 1.0f);
		
		// menuBar_2
		menuBar_2 = new MenuBar();
		menuBar_2.setImmediate(false);
		menuBar_2.setWidth("-1px");
		menuBar_2.setHeight("-1px");
		menuBars.addComponent(menuBar_2);
		
		return menuBars;
	}

	@AutoGenerated
	private Panel buildPanel() {
		// common part: create layout
		panel = new Panel();
		panel.setImmediate(false);
		panel.setWidth("100.0%");
		panel.setHeight("100.0%");
		
		// panelContent
		panelContent = new VerticalLayout();
		panelContent.setImmediate(false);
		panelContent.setWidth("100.0%");
		panelContent.setHeight("100.0%");
		panelContent.setMargin(false);
		panel.setContent(panelContent);
		
		return panel;
	}
	
}
