package de.jworks.datahub.presentation.editors;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import de.jworks.datahub.business.documents.entity.Attribute;

public class AttributeEditor extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TextArea description;
	@AutoGenerated
	private TextField label;
	@AutoGenerated
	private TextField name;
	public AttributeEditor(Attribute attribute) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		name.setNullRepresentation(null);
		description.setNullRepresentation(null);
		
		FieldGroup fieldGroup = new FieldGroup();
		fieldGroup.setItemDataSource(new BeanItem<Attribute>(attribute));
		fieldGroup.setBuffered(false);
		fieldGroup.bindMemberFields(this);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// name
		name = new TextField();
		name.setCaption("Name:");
		name.setImmediate(false);
		name.setWidth("100.0%");
		name.setHeight("-1px");
		name.setRequired(true);
		name.setInputPrompt("Name");
		mainLayout.addComponent(name);
		
		// label
		label = new TextField();
		label.setCaption("Label:");
		label.setImmediate(false);
		label.setWidth("100.0%");
		label.setHeight("-1px");
		label.setRequired(true);
		mainLayout.addComponent(label);
		
		// description
		description = new TextArea();
		description.setCaption("Description:");
		description.setImmediate(false);
		description.setWidth("100.0%");
		description.setHeight("-1px");
		description.setInputPrompt("Description");
		mainLayout.addComponent(description);
		
		return mainLayout;
	}

}
