package de.jworks.datahub.presentation.editors;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.BeanItem;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

import de.jworks.datahub.business.transform.entity.Datasink;
import de.jworks.datahub.presentation.Messages;

public class DatasinkEditor extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button closeButton;
	@AutoGenerated
	private TabSheet tabSheet;
	@AutoGenerated
	private VerticalLayout camelTab;
	@AutoGenerated
	private TextArea routeSpec;
	@AutoGenerated
	private VerticalLayout schemaTab;
	@AutoGenerated
	private DatasinkSchemaEditor schemaEditor;
	@AutoGenerated
	private VerticalLayout datasinkTab;
	@AutoGenerated
	private TextField label;
	@AutoGenerated
	private TextField name;
	public DatasinkEditor(Datasink datasink) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		datasinkTab.setMargin(new MarginInfo(true, false, false, false));
		
		schemaTab.setMargin(new MarginInfo(true, false, false, false));
		
		schemaEditor.setSchema(datasink.getSchema());
	
		camelTab.setMargin(new MarginInfo(true, false, false, false));
		
		FieldGroup fieldGroup = new FieldGroup();
		fieldGroup.setItemDataSource(new BeanItem<Datasink>(datasink));
		fieldGroup.setBuffered(false);
		fieldGroup.bindMemberFields(this);
		
		closeButton.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				((Window) getParent()).close();
			}
		});
		
		Messages.translate(this);
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet
		tabSheet = buildTabSheet();
		mainLayout.addComponent(tabSheet);
		mainLayout.setExpandRatio(tabSheet, 1.0f);
		
		// closeButton
		closeButton = new Button();
		closeButton.setCaption("Close");
		closeButton.setImmediate(true);
		closeButton.setWidth("-1px");
		closeButton.setHeight("-1px");
		mainLayout.addComponent(closeButton);
		mainLayout.setComponentAlignment(closeButton, new Alignment(6));
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet() {
		// common part: create layout
		tabSheet = new TabSheet();
		tabSheet.setStyleName("minimal");
		tabSheet.setImmediate(true);
		tabSheet.setWidth("100.0%");
		tabSheet.setHeight("100.0%");
		
		// datasinkTab
		datasinkTab = buildDatasinkTab();
		tabSheet.addTab(datasinkTab, "Datasink", null);
		
		// schemaTab
		schemaTab = buildSchemaTab();
		tabSheet.addTab(schemaTab, "Schema", null);
		
		// camelTab
		camelTab = buildCamelTab();
		tabSheet.addTab(camelTab, "Camel", null);
		
		return tabSheet;
	}

	@AutoGenerated
	private VerticalLayout buildDatasinkTab() {
		// common part: create layout
		datasinkTab = new VerticalLayout();
		datasinkTab.setImmediate(false);
		datasinkTab.setWidth("100.0%");
		datasinkTab.setHeight("-1px");
		datasinkTab.setMargin(true);
		datasinkTab.setSpacing(true);
		
		// name
		name = new TextField();
		name.setCaption("Name");
		name.setImmediate(false);
		name.setWidth("100.0%");
		name.setHeight("-1px");
		name.setRequired(true);
		datasinkTab.addComponent(name);
		
		// label
		label = new TextField();
		label.setCaption("Label");
		label.setImmediate(false);
		label.setWidth("100.0%");
		label.setHeight("-1px");
		label.setRequired(true);
		datasinkTab.addComponent(label);
		
		return datasinkTab;
	}

	@AutoGenerated
	private VerticalLayout buildSchemaTab() {
		// common part: create layout
		schemaTab = new VerticalLayout();
		schemaTab.setImmediate(false);
		schemaTab.setWidth("100.0%");
		schemaTab.setHeight("100.0%");
		schemaTab.setMargin(true);
		
		// schemaEditor
		schemaEditor = new DatasinkSchemaEditor();
		schemaEditor.setImmediate(false);
		schemaEditor.setWidth("100.0%");
		schemaEditor.setHeight("100.0%");
		schemaTab.addComponent(schemaEditor);
		schemaTab.setExpandRatio(schemaEditor, 1.0f);
		
		return schemaTab;
	}

	@AutoGenerated
	private VerticalLayout buildCamelTab() {
		// common part: create layout
		camelTab = new VerticalLayout();
		camelTab.setImmediate(false);
		camelTab.setWidth("100.0%");
		camelTab.setHeight("100.0%");
		camelTab.setMargin(true);
		
		// routeSpec
		routeSpec = new TextArea();
		routeSpec.setCaption("Route");
		routeSpec.setImmediate(false);
		routeSpec.setWidth("100.0%");
		routeSpec.setHeight("100.0%");
		camelTab.addComponent(routeSpec);
		camelTab.setExpandRatio(routeSpec, 1.0f);
		
		return camelTab;
	}

}
