package de.jworks.datahub.presentation.editors;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import de.jworks.datahub.business.datasets.entity.Element;
import de.jworks.datahub.presentation.Messages;

public class DatasetSchemaElementEditor extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout occursFields;
	@AutoGenerated
	private TextField maxOccurs;
	@AutoGenerated
	private TextField minOccurs;
	@AutoGenerated
	private TextArea description;
	@AutoGenerated
	private HorizontalLayout labels;
	@AutoGenerated
	private TextField pluralLabel;
	@AutoGenerated
	private TextField label;
	@AutoGenerated
	private TextField name;
	
	public DatasetSchemaElementEditor(Element element) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// hide occurs fields for root element
		occursFields.setVisible(element.getParent() != null);
		
		FieldGroup fieldGroup = new FieldGroup();
		fieldGroup.setItemDataSource(new BeanItem<Element>(element));
		fieldGroup.setBuffered(false);
		fieldGroup.bindMemberFields(this);
		
		Messages.translate(this);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// name
		name = new TextField();
		name.setCaption("Name:");
		name.setImmediate(false);
		name.setWidth("100.0%");
		name.setHeight("-1px");
		name.setRequired(true);
		mainLayout.addComponent(name);
		
		// labels
		labels = buildLabels();
		mainLayout.addComponent(labels);
		
		// description
		description = new TextArea();
		description.setCaption("Description:");
		description.setImmediate(false);
		description.setWidth("100.0%");
		description.setHeight("-1px");
		mainLayout.addComponent(description);
		
		// occursFields
		occursFields = buildOccursFields();
		mainLayout.addComponent(occursFields);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildLabels() {
		// common part: create layout
		labels = new HorizontalLayout();
		labels.setImmediate(false);
		labels.setWidth("100.0%");
		labels.setHeight("-1px");
		labels.setMargin(false);
		labels.setSpacing(true);
		
		// label
		label = new TextField();
		label.setCaption("Label:");
		label.setImmediate(false);
		label.setWidth("100.0%");
		label.setHeight("-1px");
		label.setRequired(true);
		labels.addComponent(label);
		
		// pluralLabel
		pluralLabel = new TextField();
		pluralLabel.setCaption("Plural Label:");
		pluralLabel.setImmediate(false);
		pluralLabel.setWidth("100.0%");
		pluralLabel.setHeight("-1px");
		labels.addComponent(pluralLabel);
		
		return labels;
	}

	@AutoGenerated
	private HorizontalLayout buildOccursFields() {
		// common part: create layout
		occursFields = new HorizontalLayout();
		occursFields.setImmediate(false);
		occursFields.setWidth("100.0%");
		occursFields.setHeight("-1px");
		occursFields.setMargin(false);
		occursFields.setSpacing(true);
		
		// minOccurs
		minOccurs = new TextField();
		minOccurs.setCaption("Min Occurs:");
		minOccurs.setImmediate(false);
		minOccurs.setWidth("100.0%");
		minOccurs.setHeight("-1px");
		occursFields.addComponent(minOccurs);
		occursFields.setExpandRatio(minOccurs, 1.0f);
		
		// maxOccurs
		maxOccurs = new TextField();
		maxOccurs.setCaption("Max Occurs:");
		maxOccurs.setImmediate(false);
		maxOccurs.setWidth("100.0%");
		maxOccurs.setHeight("-1px");
		occursFields.addComponent(maxOccurs);
		occursFields.setExpandRatio(maxOccurs, 1.0f);
		
		return occursFields;
	}

}
