package de.jworks.datahub.presentation.editors;

import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.BeanItem;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

import de.jworks.datahub.business.transform.entity.Datasink;
import de.jworks.datahub.business.transform.entity.Datasource;
import de.jworks.datahub.business.transform.entity.TransformationDefinition;

public class TransformationDefinitionEditor extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private ComboBox datasource;
	@AutoGenerated
	private ComboBox datasink;
	
	public TransformationDefinitionEditor() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		datasink.setNullSelectionAllowed(false);
	}
	
	public void setData(TransformationDefinition definition, List<Datasink> datasinks, List<Datasource> datasources) {
		for (Datasink sink : datasinks) {
			datasink.addItem(sink);
		}

		for (Datasource source : datasources) {
			datasource.addItem(source);
		}

		final FieldGroup fieldGroup = new FieldGroup();
		fieldGroup.setItemDataSource(new BeanItem<TransformationDefinition>(definition));
		fieldGroup.setBuffered(false);
		fieldGroup.bindMemberFields(this);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// datasink
		datasink = new ComboBox();
		datasink.setCaption("Datasink:");
		datasink.setImmediate(false);
		datasink.setWidth("100.0%");
		datasink.setHeight("-1px");
		datasink.setRequired(true);
		mainLayout.addComponent(datasink);
		
		// datasource
		datasource = new ComboBox();
		datasource.setCaption("Datasource:");
		datasource.setImmediate(false);
		datasource.setWidth("100.0%");
		datasource.setHeight("-1px");
		mainLayout.addComponent(datasource);
		
		return mainLayout;
	}

}
