package de.jworks.datahub.presentation.admin;

import com.porotype.iconfont.FontAwesome.Icon;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.cdi.CDIView;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Table.ColumnHeaderMode;

import de.jworks.datahub.presentation.AdminUI;

@CDIView(value = "dataflows", uis = { AdminUI.class })
public class DataflowsView extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout body;
	@AutoGenerated
	private TabSheet tabSheet;
	@AutoGenerated
	private VerticalLayout customDataflowsTab;
	@AutoGenerated
	private Button addCustomDataflowButton;
	@AutoGenerated
	private Table customDataflowsTable;
	@AutoGenerated
	private VerticalLayout queriesTab;
	@AutoGenerated
	private Button addQueryButton;
	@AutoGenerated
	private Table queriesTable;
	@AutoGenerated
	private VerticalLayout exportsTab;
	@AutoGenerated
	private Button addExportButton;
	@AutoGenerated
	private Table exportsTable;
	@AutoGenerated
	private VerticalLayout importsTab;
	@AutoGenerated
	private Button addImportButton;
	@AutoGenerated
	private Table importsTable;
	@AutoGenerated
	private Label label;
	public DataflowsView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		label.setContentMode(ContentMode.HTML);
		label.setValue(Icon.home + " / Dataflows");
		
		importsTab.setMargin(new MarginInfo(true, false, false, false));
		importsTable.setColumnHeaderMode(ColumnHeaderMode.HIDDEN);
		//addImportButton.addClickListener(new );
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setStyleName("blue");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label
		label = new Label();
		label.setStyleName("h2");
		label.setImmediate(false);
		label.setWidth("-1px");
		label.setHeight("-1px");
		label.setValue("Home / Dataflows");
		mainLayout.addComponent(label);
		
		// body
		body = buildBody();
		mainLayout.addComponent(body);
		mainLayout.setExpandRatio(body, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildBody() {
		// common part: create layout
		body = new VerticalLayout();
		body.setStyleName("white");
		body.setImmediate(false);
		body.setWidth("100.0%");
		body.setHeight("100.0%");
		body.setMargin(true);
		
		// tabSheet
		tabSheet = buildTabSheet();
		body.addComponent(tabSheet);
		
		return body;
	}

	@AutoGenerated
	private TabSheet buildTabSheet() {
		// common part: create layout
		tabSheet = new TabSheet();
		tabSheet.setStyleName("minimal");
		tabSheet.setImmediate(true);
		tabSheet.setWidth("100.0%");
		tabSheet.setHeight("100.0%");
		
		// importsTab
		importsTab = buildImportsTab();
		tabSheet.addTab(importsTab, "Imports", null);
		
		// exportsTab
		exportsTab = buildExportsTab();
		tabSheet.addTab(exportsTab, "Exports", null);
		
		// queriesTab
		queriesTab = buildQueriesTab();
		tabSheet.addTab(queriesTab, "Queries", null);
		
		// customDataflowsTab
		customDataflowsTab = buildCustomDataflowsTab();
		tabSheet.addTab(customDataflowsTab, "Dataflows", null);
		
		return tabSheet;
	}

	@AutoGenerated
	private VerticalLayout buildImportsTab() {
		// common part: create layout
		importsTab = new VerticalLayout();
		importsTab.setImmediate(false);
		importsTab.setWidth("100.0%");
		importsTab.setHeight("100.0%");
		importsTab.setMargin(true);
		importsTab.setSpacing(true);
		
		// importsTable
		importsTable = new Table();
		importsTable.setImmediate(false);
		importsTable.setWidth("100.0%");
		importsTable.setHeight("100.0%");
		importsTab.addComponent(importsTable);
		importsTab.setExpandRatio(importsTable, 1.0f);
		
		// addImportButton
		addImportButton = new Button();
		addImportButton.setStyleName("link");
		addImportButton.setCaption("Add Import");
		addImportButton.setImmediate(true);
		addImportButton.setWidth("-1px");
		addImportButton.setHeight("-1px");
		importsTab.addComponent(addImportButton);
		
		return importsTab;
	}

	@AutoGenerated
	private VerticalLayout buildExportsTab() {
		// common part: create layout
		exportsTab = new VerticalLayout();
		exportsTab.setImmediate(false);
		exportsTab.setWidth("100.0%");
		exportsTab.setHeight("100.0%");
		exportsTab.setMargin(true);
		exportsTab.setSpacing(true);
		
		// exportsTable
		exportsTable = new Table();
		exportsTable.setImmediate(false);
		exportsTable.setWidth("100.0%");
		exportsTable.setHeight("100.0%");
		exportsTab.addComponent(exportsTable);
		exportsTab.setExpandRatio(exportsTable, 1.0f);
		
		// addExportButton
		addExportButton = new Button();
		addExportButton.setStyleName("link");
		addExportButton.setCaption("Add Export");
		addExportButton.setImmediate(true);
		addExportButton.setWidth("-1px");
		addExportButton.setHeight("-1px");
		exportsTab.addComponent(addExportButton);
		
		return exportsTab;
	}

	@AutoGenerated
	private VerticalLayout buildQueriesTab() {
		// common part: create layout
		queriesTab = new VerticalLayout();
		queriesTab.setImmediate(false);
		queriesTab.setWidth("100.0%");
		queriesTab.setHeight("100.0%");
		queriesTab.setMargin(true);
		queriesTab.setSpacing(true);
		
		// queriesTable
		queriesTable = new Table();
		queriesTable.setImmediate(false);
		queriesTable.setWidth("100.0%");
		queriesTable.setHeight("100.0%");
		queriesTab.addComponent(queriesTable);
		queriesTab.setExpandRatio(queriesTable, 1.0f);
		
		// addQueryButton
		addQueryButton = new Button();
		addQueryButton.setStyleName("link");
		addQueryButton.setCaption("Add Query");
		addQueryButton.setImmediate(true);
		addQueryButton.setWidth("-1px");
		addQueryButton.setHeight("-1px");
		queriesTab.addComponent(addQueryButton);
		
		return queriesTab;
	}

	@AutoGenerated
	private VerticalLayout buildCustomDataflowsTab() {
		// common part: create layout
		customDataflowsTab = new VerticalLayout();
		customDataflowsTab.setImmediate(false);
		customDataflowsTab.setWidth("100.0%");
		customDataflowsTab.setHeight("100.0%");
		customDataflowsTab.setMargin(true);
		customDataflowsTab.setSpacing(true);
		
		// customDataflowsTable
		customDataflowsTable = new Table();
		customDataflowsTable.setImmediate(false);
		customDataflowsTable.setWidth("100.0%");
		customDataflowsTable.setHeight("100.0%");
		customDataflowsTab.addComponent(customDataflowsTable);
		customDataflowsTab.setExpandRatio(customDataflowsTable, 1.0f);
		
		// addCustomDataflowButton
		addCustomDataflowButton = new Button();
		addCustomDataflowButton.setStyleName("link");
		addCustomDataflowButton.setCaption("Add Custom Dataflow");
		addCustomDataflowButton.setImmediate(true);
		addCustomDataflowButton.setWidth("-1px");
		addCustomDataflowButton.setHeight("-1px");
		customDataflowsTab.addComponent(addCustomDataflowButton);
		
		return customDataflowsTab;
	}

}
