package de.jworks.datahub.presentation.admin;

import javax.inject.Inject;

import com.porotype.iconfont.FontAwesome.Icon;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.cdi.CDIView;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import de.jworks.datahub.business.datasets.boundary.DatasetService;
import de.jworks.datahub.business.datasets.entity.DatasetGroup;
import de.jworks.datahub.presentation.AdminUI;
import de.jworks.datahub.presentation.editors.DatasetSchemaEditor;

@CDIView(value = "datasetgroup", supportsParameters = true, uis = { AdminUI.class })
public class DatasetGroupView extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout body;
	@AutoGenerated
	private HorizontalLayout buttons;
	@AutoGenerated
	private Button cancelButton;
	@AutoGenerated
	private Button saveButton;
	@AutoGenerated
	private TabSheet tabSheet;
	@AutoGenerated
	private VerticalLayout schemaTab;
	@AutoGenerated
	private DatasetSchemaEditor schemaEditor;
	@AutoGenerated
	private VerticalLayout datasetGroupTab;
	@AutoGenerated
	private TextArea descriptionField;
	@AutoGenerated
	private TextField nameField;
	@AutoGenerated
	private Label label;
	@Inject
	DatasetService datasetService;
	
	private DatasetGroup datasetGroup;
	
	public DatasetGroupView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		label.setContentMode(ContentMode.HTML);
		
		datasetGroupTab.setMargin(new MarginInfo(true, false, false, false));
		
		schemaTab.setMargin(new MarginInfo(true, false, false, false));
	}

	@Override
	public void enter(ViewChangeEvent event) {
		try {
			long datasetGroupId = Long.parseLong(event.getParameters());
			datasetGroup = datasetService.getDatasetGroup(datasetGroupId);
			
			label.setValue(Icon.home + " / Dataset Groups / " + datasetGroup.getName());
		} catch (Exception e) {
			datasetGroup = new DatasetGroup();
			
			label.setValue(Icon.home + " / Dataset Groups / New Dataset Group");
		}
		
		schemaEditor.setDocumentSchema(datasetGroup.getSchema());
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setStyleName("blue");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label
		label = new Label();
		label.setStyleName("h2");
		label.setImmediate(false);
		label.setWidth("-1px");
		label.setHeight("-1px");
		label.setValue("Home / Dataset Groups / Dataset Group");
		mainLayout.addComponent(label);
		
		// body
		body = buildBody();
		mainLayout.addComponent(body);
		mainLayout.setExpandRatio(body, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildBody() {
		// common part: create layout
		body = new VerticalLayout();
		body.setStyleName("white");
		body.setImmediate(false);
		body.setWidth("100.0%");
		body.setHeight("100.0%");
		body.setMargin(true);
		
		// tabSheet
		tabSheet = buildTabSheet();
		body.addComponent(tabSheet);
		body.setExpandRatio(tabSheet, 1.0f);
		
		// buttons
		buttons = buildButtons();
		body.addComponent(buttons);
		
		return body;
	}

	@AutoGenerated
	private TabSheet buildTabSheet() {
		// common part: create layout
		tabSheet = new TabSheet();
		tabSheet.setStyleName("minimal");
		tabSheet.setImmediate(true);
		tabSheet.setWidth("100.0%");
		tabSheet.setHeight("100.0%");
		
		// datasetGroupTab
		datasetGroupTab = buildDatasetGroupTab();
		tabSheet.addTab(datasetGroupTab, "Dataset Group", null);
		
		// schemaTab
		schemaTab = buildSchemaTab();
		tabSheet.addTab(schemaTab, "Schema", null);
		
		return tabSheet;
	}

	@AutoGenerated
	private VerticalLayout buildDatasetGroupTab() {
		// common part: create layout
		datasetGroupTab = new VerticalLayout();
		datasetGroupTab.setImmediate(false);
		datasetGroupTab.setWidth("100.0%");
		datasetGroupTab.setHeight("-1px");
		datasetGroupTab.setMargin(true);
		datasetGroupTab.setSpacing(true);
		
		// nameField
		nameField = new TextField();
		nameField.setCaption("Name");
		nameField.setImmediate(false);
		nameField.setWidth("100.0%");
		nameField.setHeight("-1px");
		datasetGroupTab.addComponent(nameField);
		
		// descriptionField
		descriptionField = new TextArea();
		descriptionField.setCaption("Description");
		descriptionField.setImmediate(false);
		descriptionField.setWidth("100.0%");
		descriptionField.setHeight("-1px");
		datasetGroupTab.addComponent(descriptionField);
		
		return datasetGroupTab;
	}

	@AutoGenerated
	private VerticalLayout buildSchemaTab() {
		// common part: create layout
		schemaTab = new VerticalLayout();
		schemaTab.setImmediate(false);
		schemaTab.setWidth("100.0%");
		schemaTab.setHeight("100.0%");
		schemaTab.setMargin(true);
		schemaTab.setSpacing(true);
		
		// schemaEditor
		schemaEditor = new DatasetSchemaEditor();
		schemaEditor.setImmediate(false);
		schemaEditor.setWidth("100.0%");
		schemaEditor.setHeight("100.0%");
		schemaTab.addComponent(schemaEditor);
		schemaTab.setExpandRatio(schemaEditor, 1.0f);
		
		return schemaTab;
	}

	@AutoGenerated
	private HorizontalLayout buildButtons() {
		// common part: create layout
		buttons = new HorizontalLayout();
		buttons.setImmediate(false);
		buttons.setWidth("-1px");
		buttons.setHeight("-1px");
		buttons.setMargin(false);
		buttons.setSpacing(true);
		
		// saveButton
		saveButton = new Button();
		saveButton.setStyleName("primary");
		saveButton.setCaption("Save");
		saveButton.setImmediate(false);
		saveButton.setWidth("-1px");
		saveButton.setHeight("-1px");
		buttons.addComponent(saveButton);
		
		// cancelButton
		cancelButton = new Button();
		cancelButton.setCaption("Cancel");
		cancelButton.setImmediate(false);
		cancelButton.setWidth("-1px");
		cancelButton.setHeight("-1px");
		buttons.addComponent(cancelButton);
		
		return buttons;
	}

}
