package de.jworks.datahub.presentation.admin;

import com.porotype.iconfont.FontAwesome.Icon;
import com.porotype.iconfont.FontAwesome.IconVariant;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;

public class Header2 extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private TextField searchField;
	@AutoGenerated
	private Button actionsButton;
	@AutoGenerated
	private Button transformationsButton;
	@AutoGenerated
	private Button connectorsButton;
	@AutoGenerated
	private Button datasetsButton;
	@AutoGenerated
	private Button usersButton;
	@AutoGenerated
	private Label label_1;
	public Header2() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		label_1.setContentMode(ContentMode.HTML);
		label_1.setValue(Icon.globe.variant(IconVariant.SIZE_LARGE) + " Data Hub");
		
		usersButton.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().getNavigator().navigateTo("users2");
			}
		});
		
		datasetsButton.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().getNavigator().navigateTo("datasets");
			}
		});
		
		connectorsButton.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().getNavigator().navigateTo("connectors");
			}
		});
		
		transformationsButton.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().getNavigator().navigateTo("transformations");
			}
		});
		
		actionsButton.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().getNavigator().navigateTo("actions");
			}
		});
	}
	
	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("70px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("70px");
		
		// label_1
		label_1 = new Label();
		label_1.setStyleName("h1");
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Data Hub");
		mainLayout.addComponent(label_1);
		mainLayout.setExpandRatio(label_1, 1.0f);
		mainLayout.setComponentAlignment(label_1, new Alignment(33));
		
		// usersButton
		usersButton = new Button();
		usersButton.setStyleName("link");
		usersButton.setCaption("Users");
		usersButton.setImmediate(true);
		usersButton.setWidth("-1px");
		usersButton.setHeight("-1px");
		mainLayout.addComponent(usersButton);
		mainLayout.setComponentAlignment(usersButton, new Alignment(48));
		
		// datasetsButton
		datasetsButton = new Button();
		datasetsButton.setStyleName("link");
		datasetsButton.setCaption("Datasets");
		datasetsButton.setImmediate(true);
		datasetsButton.setWidth("-1px");
		datasetsButton.setHeight("-1px");
		mainLayout.addComponent(datasetsButton);
		mainLayout.setComponentAlignment(datasetsButton, new Alignment(48));
		
		// connectorsButton
		connectorsButton = new Button();
		connectorsButton.setStyleName("link");
		connectorsButton.setCaption("Connectors");
		connectorsButton.setImmediate(true);
		connectorsButton.setWidth("-1px");
		connectorsButton.setHeight("-1px");
		mainLayout.addComponent(connectorsButton);
		mainLayout.setComponentAlignment(connectorsButton, new Alignment(48));
		
		// transformationsButton
		transformationsButton = new Button();
		transformationsButton.setStyleName("link");
		transformationsButton.setCaption("Transformations");
		transformationsButton.setImmediate(true);
		transformationsButton.setWidth("-1px");
		transformationsButton.setHeight("-1px");
		mainLayout.addComponent(transformationsButton);
		mainLayout.setComponentAlignment(transformationsButton, new Alignment(
				48));
		
		// actionsButton
		actionsButton = new Button();
		actionsButton.setStyleName("link");
		actionsButton.setCaption("Actions");
		actionsButton.setImmediate(true);
		actionsButton.setWidth("-1px");
		actionsButton.setHeight("-1px");
		mainLayout.addComponent(actionsButton);
		mainLayout.setComponentAlignment(actionsButton, new Alignment(48));
		
		// searchField
		searchField = new TextField();
		searchField.setImmediate(false);
		searchField.setWidth("-1px");
		searchField.setHeight("-1px");
		searchField.setInputPrompt("Search");
		mainLayout.addComponent(searchField);
		mainLayout.setExpandRatio(searchField, 1.0f);
		mainLayout.setComponentAlignment(searchField, new Alignment(34));
		
		return mainLayout;
	}

}
