package de.jworks.datahub.presentation.admin;

import com.porotype.iconfont.FontAwesome.Icon;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.cdi.CDIView;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

@CDIView(value = "transformations", uis = { AdminUI.class })
public class TransformationsView extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout body;
	@AutoGenerated
	private TabSheet tabSheet;
	@AutoGenerated
	private VerticalLayout transformationsTab;
	@AutoGenerated
	private Button addTransformationButton;
	@AutoGenerated
	private Table transformationsTable;
	@AutoGenerated
	private Label label;
	public TransformationsView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		label.setContentMode(ContentMode.HTML);
		label.setValue(Icon.home + " / Transformations");
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setStyleName("blue");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label
		label = new Label();
		label.setStyleName("h2");
		label.setImmediate(false);
		label.setWidth("-1px");
		label.setHeight("-1px");
		label.setValue("Home / Connectors");
		mainLayout.addComponent(label);
		
		// body
		body = buildBody();
		mainLayout.addComponent(body);
		mainLayout.setExpandRatio(body, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildBody() {
		// common part: create layout
		body = new VerticalLayout();
		body.setStyleName("white");
		body.setImmediate(false);
		body.setWidth("100.0%");
		body.setHeight("100.0%");
		body.setMargin(true);
		
		// tabSheet
		tabSheet = buildTabSheet();
		body.addComponent(tabSheet);
		
		return body;
	}

	@AutoGenerated
	private TabSheet buildTabSheet() {
		// common part: create layout
		tabSheet = new TabSheet();
		tabSheet.setStyleName("minimal");
		tabSheet.setImmediate(true);
		tabSheet.setWidth("100.0%");
		tabSheet.setHeight("100.0%");
		
		// transformationsTab
		transformationsTab = buildTransformationsTab();
		tabSheet.addTab(transformationsTab, "Transformations", null);
		
		return tabSheet;
	}

	@AutoGenerated
	private VerticalLayout buildTransformationsTab() {
		// common part: create layout
		transformationsTab = new VerticalLayout();
		transformationsTab.setImmediate(false);
		transformationsTab.setWidth("100.0%");
		transformationsTab.setHeight("100.0%");
		transformationsTab.setMargin(true);
		transformationsTab.setSpacing(true);
		
		// transformationsTable
		transformationsTable = new Table();
		transformationsTable.setImmediate(false);
		transformationsTable.setWidth("100.0%");
		transformationsTable.setHeight("100.0%");
		transformationsTab.addComponent(transformationsTable);
		transformationsTab.setExpandRatio(transformationsTable, 1.0f);
		
		// addTransformationButton
		addTransformationButton = new Button();
		addTransformationButton.setStyleName("link");
		addTransformationButton.setCaption("Add Transformation");
		addTransformationButton.setImmediate(true);
		addTransformationButton.setWidth("-1px");
		addTransformationButton.setHeight("-1px");
		transformationsTab.addComponent(addTransformationButton);
		
		return transformationsTab;
	}

}
