package de.jworks.datahub.presentation.admin;

import javax.inject.Inject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.cdi.CDIView;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.BeanItem;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

import de.jworks.datahub.business.common.boundary.UserService;
import de.jworks.datahub.business.common.entity.UserGroup;
import de.jworks.datahub.presentation.AdminUI;

@CDIView(value = "usergroup!", supportsParameters = true, uis = { AdminUI.class })
public class UserGroupView extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout body;
	@AutoGenerated
	private HorizontalLayout buttons;
	@AutoGenerated
	private Button cancelButton;
	@AutoGenerated
	private Button saveButton;
	@AutoGenerated
	private TabSheet tabSheet;
	@AutoGenerated
	private VerticalLayout usersTab;
	@AutoGenerated
	private VerticalLayout userGroupTab;
	@AutoGenerated
	private VerticalLayout userGroupForm;
	@AutoGenerated
	private TextField name;
	@AutoGenerated
	private Label label;
	
	@Inject
	UserService userService;
	
	private FieldGroup fieldGroup;
	
	private UserGroup userGroup;
	
	public UserGroupView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		label.setContentMode(ContentMode.HTML);
		
		userGroupTab.setMargin(new MarginInfo(true, false, false, false));
		
		usersTab.setMargin(new MarginInfo(true, false, false, false));
		
		fieldGroup = new FieldGroup();
		
		saveButton.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				try {
					fieldGroup.commit();
					if (userGroup.getId() == null) {
						userService.addUserGroup(userGroup);
					} else {
						userService.updateUserGroup(userGroup);
					}
					UI.getCurrent().getNavigator().navigateTo("users!/");
				} catch (Exception e) {
					Notification.show("Error", e.getMessage(), Notification.Type.ERROR_MESSAGE);
				}
			}
		});
		
		cancelButton.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				UI.getCurrent().getNavigator().navigateTo("users!/");
			}
		});
	}

	@Override
	public void enter(ViewChangeEvent event) {
		try {
			try {
				long userGroupId = Long.parseLong(event.getParameters());
				userGroup = userService.getUserGroup(userGroupId);
			} catch (Exception e) {
				userGroup = new UserGroup();
				userGroup.setName("New User Group");
			}
			
			label.setValue("<li class='icon-home'></li> / Users / " + userGroup.getName());
			
			fieldGroup.setItemDataSource(new BeanItem<UserGroup>(userGroup));
			fieldGroup.bindMemberFields(this);
		} catch (Exception e) {
			UI.getCurrent().getNavigator().navigateTo("users!/");
		}
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setStyleName("blue");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label
		label = new Label();
		label.setStyleName("h2");
		label.setImmediate(false);
		label.setWidth("-1px");
		label.setHeight("-1px");
		label.setValue("Home / Users / User");
		mainLayout.addComponent(label);
		
		// body
		body = buildBody();
		mainLayout.addComponent(body);
		mainLayout.setExpandRatio(body, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildBody() {
		// common part: create layout
		body = new VerticalLayout();
		body.setStyleName("white");
		body.setImmediate(false);
		body.setWidth("100.0%");
		body.setHeight("100.0%");
		body.setMargin(true);
		body.setSpacing(true);
		
		// tabSheet
		tabSheet = buildTabSheet();
		body.addComponent(tabSheet);
		body.setExpandRatio(tabSheet, 1.0f);
		
		// buttons
		buttons = buildButtons();
		body.addComponent(buttons);
		
		return body;
	}

	@AutoGenerated
	private TabSheet buildTabSheet() {
		// common part: create layout
		tabSheet = new TabSheet();
		tabSheet.setStyleName("minimal");
		tabSheet.setImmediate(true);
		tabSheet.setWidth("100.0%");
		tabSheet.setHeight("100.0%");
		
		// userGroupTab
		userGroupTab = buildUserGroupTab();
		tabSheet.addTab(userGroupTab, "User Group", null);
		
		// usersTab
		usersTab = new VerticalLayout();
		usersTab.setImmediate(false);
		usersTab.setWidth("100.0%");
		usersTab.setHeight("100.0%");
		usersTab.setMargin(true);
		tabSheet.addTab(usersTab, "Users", null);
		
		return tabSheet;
	}

	@AutoGenerated
	private VerticalLayout buildUserGroupTab() {
		// common part: create layout
		userGroupTab = new VerticalLayout();
		userGroupTab.setImmediate(false);
		userGroupTab.setWidth("100.0%");
		userGroupTab.setHeight("100.0%");
		userGroupTab.setMargin(true);
		userGroupTab.setSpacing(true);
		
		// userGroupForm
		userGroupForm = buildUserGroupForm();
		userGroupTab.addComponent(userGroupForm);
		
		return userGroupTab;
	}

	@AutoGenerated
	private VerticalLayout buildUserGroupForm() {
		// common part: create layout
		userGroupForm = new VerticalLayout();
		userGroupForm.setImmediate(false);
		userGroupForm.setWidth("100.0%");
		userGroupForm.setHeight("-1px");
		userGroupForm.setMargin(false);
		userGroupForm.setSpacing(true);
		
		// name
		name = new TextField();
		name.setCaption("Name");
		name.setImmediate(false);
		name.setWidth("100.0%");
		name.setHeight("-1px");
		name.setRequired(true);
		userGroupForm.addComponent(name);
		
		return userGroupForm;
	}

	@AutoGenerated
	private HorizontalLayout buildButtons() {
		// common part: create layout
		buttons = new HorizontalLayout();
		buttons.setImmediate(false);
		buttons.setWidth("-1px");
		buttons.setHeight("-1px");
		buttons.setMargin(false);
		buttons.setSpacing(true);
		
		// saveButton
		saveButton = new Button();
		saveButton.setStyleName("primary");
		saveButton.setCaption("Save");
		saveButton.setImmediate(true);
		saveButton.setWidth("-1px");
		saveButton.setHeight("-1px");
		buttons.addComponent(saveButton);
		
		// cancelButton
		cancelButton = new Button();
		cancelButton.setCaption("Cancel");
		cancelButton.setImmediate(true);
		cancelButton.setWidth("-1px");
		cancelButton.setHeight("-1px");
		buttons.addComponent(cancelButton);
		
		return buttons;
	}

}
