package de.jworks.datahub.presentation;

import javax.inject.Inject;

import com.porotype.iconfont.FontAwesome.Icon;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.cdi.access.JaasAccessControl;
import com.vaadin.server.Page;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.UI;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;

import de.jworks.datahub.business.common.entity.User;

public class AccountHeader extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private MenuBar menuBar;
	
	@Inject
	User user;
	
	public AccountHeader() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@Override
	public void attach() {
		super.attach();

		menuBar.setAutoOpen(true);
		menuBar.setHtmlContentAllowed(true);
		
		MenuItem showProfileItem = menuBar.addItem(Icon.user + " " + user.getFullName(), new Command() {
			@Override
			public void menuSelected(MenuItem selectedItem) {
				UI.getCurrent().getNavigator().navigateTo("user-show/" + user.getName());
			}
		});
		showProfileItem.setDescription("Show Profile");
		
		MenuItem dashboardItem = menuBar.addItem(Icon.dashboard + " 0", null);
		dashboardItem.setDescription("Dashboard (0 new items)");
		
		MenuItem editProfileItem = menuBar.addItem(Icon.cog + "", null);
		editProfileItem.setDescription("Edit Profile");
		
		MenuItem signOutItem = menuBar.addItem(Icon.signout + "", new Command() {
			@Override
			public void menuSelected(MenuItem selectedItem) {
				try {
					JaasAccessControl.logout();
					Page.getCurrent().reload();
				} catch (Exception e) {
					// TODO: handle exception
				}
			}
		});
		signOutItem.setDescription("Sign Out");
	}
	
	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setStyleName("v-menubar");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// menuBar
		menuBar = new MenuBar();
		menuBar.setImmediate(false);
		menuBar.setWidth("-1px");
		menuBar.setHeight("-1px");
		mainLayout.addComponent(menuBar);
		mainLayout.setComponentAlignment(menuBar, new Alignment(6));
		
		return mainLayout;
	}

}
