package de.jworks.datahub.presentation;

import javax.servlet.ServletException;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.cdi.CDIView;
import com.vaadin.cdi.access.JaasAccessControl;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.server.Page;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@CDIView("login")
public class UserLoginView extends CustomComponent {
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout signInDialog;
	@AutoGenerated
	private HorizontalLayout signInForm;
	@AutoGenerated
	private Button signInButton;
	@AutoGenerated
	private PasswordField passwordField;
	@AutoGenerated
	private TextField usernameField;
	@AutoGenerated
	private HorizontalLayout headers;
	@AutoGenerated
	private Label header2;
	@AutoGenerated
	private Label header1;
	
	public UserLoginView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		Messages.translate(this);
		
		usernameField.setValue("admin");
		passwordField.setValue("passme");
		
		signInButton.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				try {
					JaasAccessControl.login(usernameField.getValue(), passwordField.getValue());
					Page.getCurrent().reload();
				} catch (ServletException e) {
					signInForm.setCaption(e.getMessage());
				}
			}
		});
		signInButton.setClickShortcut(KeyCode.ENTER);
		
		usernameField.focus();
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setStyleName("blue");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// signInDialog
		signInDialog = buildSignInDialog();
		mainLayout.addComponent(signInDialog);
		mainLayout.setComponentAlignment(signInDialog, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildSignInDialog() {
		// common part: create layout
		signInDialog = new VerticalLayout();
		signInDialog.setStyleName("white");
		signInDialog.setImmediate(false);
		signInDialog.setWidth("-1px");
		signInDialog.setHeight("-1px");
		signInDialog.setMargin(true);
		signInDialog.setSpacing(true);
		
		// headers
		headers = buildHeaders();
		signInDialog.addComponent(headers);
		
		// signInForm
		signInForm = buildSignInForm();
		signInDialog.addComponent(signInForm);
		
		return signInDialog;
	}

	@AutoGenerated
	private HorizontalLayout buildHeaders() {
		// common part: create layout
		headers = new HorizontalLayout();
		headers.setImmediate(false);
		headers.setWidth("100.0%");
		headers.setHeight("-1px");
		headers.setMargin(false);
		
		// header1
		header1 = new Label();
		header1.setStyleName("h1");
		header1.setImmediate(false);
		header1.setWidth("-1px");
		header1.setHeight("-1px");
		header1.setValue("Welcome");
		headers.addComponent(header1);
		headers.setComponentAlignment(header1, new Alignment(33));
		
		// header2
		header2 = new Label();
		header2.setStyleName("h2");
		header2.setImmediate(false);
		header2.setWidth("-1px");
		header2.setHeight("-1px");
		header2.setValue("Data Hub");
		headers.addComponent(header2);
		headers.setComponentAlignment(header2, new Alignment(34));
		
		return headers;
	}

	@AutoGenerated
	private HorizontalLayout buildSignInForm() {
		// common part: create layout
		signInForm = new HorizontalLayout();
		signInForm.setImmediate(false);
		signInForm.setWidth("-1px");
		signInForm.setHeight("-1px");
		signInForm.setMargin(false);
		signInForm.setSpacing(true);
		
		// usernameField
		usernameField = new TextField();
		usernameField.setCaption("Username");
		usernameField.setImmediate(false);
		usernameField.setWidth("-1px");
		usernameField.setHeight("-1px");
		signInForm.addComponent(usernameField);
		signInForm.setComponentAlignment(usernameField, new Alignment(9));
		
		// passwordField
		passwordField = new PasswordField();
		passwordField.setCaption("Password");
		passwordField.setImmediate(false);
		passwordField.setWidth("-1px");
		passwordField.setHeight("-1px");
		signInForm.addComponent(passwordField);
		signInForm.setComponentAlignment(passwordField, new Alignment(9));
		
		// signInButton
		signInButton = new Button();
		signInButton.setStyleName("primary");
		signInButton.setCaption("Sign In");
		signInButton.setImmediate(true);
		signInButton.setWidth("-1px");
		signInButton.setHeight("-1px");
		signInForm.addComponent(signInButton);
		signInForm.setComponentAlignment(signInButton, new Alignment(9));
		
		return signInForm;
	}

}
